/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_1;

/**
 *
 * @author hanchaelyeong
 */

import javax.swing.*;

import java.awt.*;

public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle("ContentPane과 JFrame");//프레임 타이틀달기
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //프레임 윈도를 닫으면 프로그램을 종료하도록 설정
        
        Container contentPane = getContentPane(); // 컨텐트 팬을 알아낸다
        contentPane.setBackground(Color.ORANGE); // 컨텐트팬의 색을 오렌지색으로
        contentPane.setLayout(new FlowLayout()); //컨텐트팬에 FlowLayout 배치관리자달기
        /*
        배치관리자
        ->배치관리자는 java.awt 패키지에 존재하는 클래스들이며, 이들을 사용하기 위해서는 
        "import java.awt.*;" 필요하다.
        
        ->FlowLayout
          컨테이너에 부착되는 순서대로 왼쪽에서 오른쪽으로 컴포넌트를 배치
          공간이 없으면 아래로 내려와서 다시 왼쪽에서 오른쪽 배치
        
        ->BorderLayout
          컨테이너의 공간을 동,서,남,북,중앙의 5개의 영역으로 나누고 응용프로그램에서 쩡한 영역에
          컴포넌트를배치 
          5개의 영역중 하나를 반드시 지정하여야한다. 지정X 중앙에 배치
        
        ->GridLayout
          컨테이너 공간을 동일한 크키의 2차원 격자로 나누고, 컴포넌트가 삽입되는 순서대로 좌에서 우로
          다시 위에서 나래로 배치한다 
        
        ->CardLayout
          컨테이너의 공간에 카드를 쌓아 놓은 듯이 컴포넌트를 포개어 배치 
        
        */
    
        
        contentPane.add(new JButton("OK"));     //ok     버튼달기
        contentPane.add(new JButton("Cancel")); //Cancel 버튼달기
        contentPane.add(new JButton("Ignore")); //Ignore 버튼달기 
        
        setSize(300,150); //프레임 크기 300*150 설정
        setVisible(true); //화면에 프레임 출
    }
    
    public static void main(String[] args){
      MainFrame frame = new MainFrame();
    }
    
        
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

